// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAY02kOUuRs5GPDqxJo61urN-see0vNvFM',
    appId: '1:75558830533:web:e3d14ff3a5e8311495cbac',
    messagingSenderId: '75558830533',
    projectId: 'global-infocloud--task',
    authDomain: 'global-infocloud--task.firebaseapp.com',
    storageBucket: 'global-infocloud--task.appspot.com',
    measurementId: 'G-QYQ75NYD27',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqQNpek6lRO7Q7sagHmUcZgmPCi4bbtjc',
    appId: '1:75558830533:android:f9404fbbc3339ba795cbac',
    messagingSenderId: '75558830533',
    projectId: 'global-infocloud--task',
    storageBucket: 'global-infocloud--task.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtDXGOovVyhPUT8Z6GE6llZsxhckym-SY',
    appId: '1:75558830533:ios:25115baa6e68577395cbac',
    messagingSenderId: '75558830533',
    projectId: 'global-infocloud--task',
    storageBucket: 'global-infocloud--task.appspot.com',
    iosBundleId: 'com.example.globalinfocloudTask',
  );
}
